apiVersion: v1
kind: Secret
metadata:
  name: async-booking-system-secret
type: Opaque
stringData:
  DB_USERNAME: "booking_user"
  DB_PASSWORD: "booking_password"
  RABBITMQ_USERNAME: "booking_user"
  RABBITMQ_PASSWORD: "booking_password"
