create table resources (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    description text,
    created_at timestamp not null,
    updated_at timestamp not null
);
