create table bookings (
    id bigint generated by default as identity primary key,
    resource_id bigint not null,
    user_id bigint not null,
    start_time timestamp not null,
    end_time timestamp not null,
    status varchar(32) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_bookings_resource
        foreign key (resource_id) references resources (id),
    constraint chk_bookings_time_range
        check (start_time < end_time),
    constraint chk_bookings_status
        check (status in ('BOOKED', 'CANCELLED')),
    constraint uq_bookings_resource_slot
        unique (resource_id, start_time, end_time)
);

create index idx_bookings_resource_id on bookings (resource_id);
