create table booking_requests (
    id bigint generated by default as identity primary key,
    request_id varchar(128) not null,
    resource_id bigint not null,
    user_id bigint not null,
    start_time timestamp not null,
    end_time timestamp not null,
    status varchar(32) not null,
    failure_reason text,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uq_booking_requests_request_id
        unique (request_id),
    constraint fk_booking_requests_resource
        foreign key (resource_id) references resources (id),
    constraint chk_booking_requests_time_range
        check (start_time < end_time),
    constraint chk_booking_requests_status
        check (status in ('PENDING', 'PROCESSING', 'BOOKED', 'REJECTED', 'FAILED'))
);

create index idx_booking_requests_resource_id on booking_requests (resource_id);
