create table processed_messages (
    id bigint generated by default as identity primary key,
    message_id varchar(128) not null,
    consumer_name varchar(128) not null,
    processed_at timestamp not null,
    constraint uq_processed_messages_message_consumer
        unique (message_id, consumer_name)
);
